CAPITAL = 200000
RISK_PER_TRADE = 0.01
DAILY_MAX_LOSS = 0.02
MAX_TRADES_PER_DAY = 3

# SYMBOLS = ["NIFTYBEES", "BANKBEES", "ITBEES"]
SYMBOLS = ["NIFTY 50", "BANK NIFTY"]

TIMEFRAME = "5minute"
FAST_EMA = 9
SLOW_EMA = 21
TRAIL_SL_PCT = 0.4
ADX_THRESHOLD = 20

START_TIME = (9, 20)
END_TIME = (15, 10)
