import os
from pathlib import Path
try:
	from dotenv import load_dotenv, set_key
except Exception:
	load_dotenv = None
	set_key = None
from kiteconnect import KiteConnect

# load .env if python-dotenv is available
ROOT = Path(__file__).resolve().parents[0]
if load_dotenv:
	load_dotenv(ROOT / ".env")

api_key = os.getenv("API_KEY") or input("Enter API_KEY: ")
api_secret = os.getenv("API_SECRET") or input("Enter API_SECRET: ")

kite = KiteConnect(api_key=api_key)
print("Open this URL in a browser and login:")
print(kite.login_url())

request_token = input("Enter request token: ")
data = kite.generate_session(request_token, api_secret=api_secret)
access_token = data.get("access_token")
print("Access token:", access_token)

# Save to .env for convenience
env_path = ROOT / ".env"
if not env_path.exists():
	env_path.write_text("# generated by generate_token.py\n")

if set_key:
	set_key(env_path, "ACCESS_TOKEN", access_token)
	print(f"Saved ACCESS_TOKEN to {env_path}. Do not commit this file to git.")
else:
	# fallback: append to .env
	with env_path.open("a") as f:
		f.write(f"ACCESS_TOKEN={access_token}\n")
	print(f"Appended ACCESS_TOKEN to {env_path} (python-dotenv not installed). Do not commit this file to git.")
